### PR TITLE
Extended parsing on HAProxy.prototype.parse. 

### PR DESCRIPTION
**Pull request by gshively11**
The "using" parameter now also supports "string", "array", and a custom function.

Also fixed an edge case exception with the object parser when a socket command did not contain a `:` in the response.

I've been using these changes in one of my projects with success.  However, I wasn't able to run the tests locally since I don't have HAProxy installed on my laptop. If there are any test failures due to my changes just let me know and I'll fix em.

### CODE REVIEW

**Comment by 3rd-Eden** [comment]
@gshively11 Is there any way you could add a test for this?

**Comment by gshively11** [comment]
Sure, I can give it a shot.  The tests weren't running for me locally, but I can just rely on travis to verify.

**Comment by gshively11** [comment]
Added a few extra tests on existing functionality while I was in the area. Let me know if the tests/changes are acceptable.

**Comment by 3rd-Eden** [comment]
You're amazing. Ill look at it when I get home.

**Comment by 3rd-Eden** [comment]
I'll bump it to a minor as it adds new features to the module.

**Pull request merged**
